services:
  db:
    image: postgres:16
    container_name: baruashub_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: baruashub
    ports:
      - "5432:5432"
    volumes:
      - baruashub_pgdata:/var/lib/postgresql/data

volumes:
  baruashub_pgdata:
