services:
  web:
    build:
      context: ../../app
      args:
        DATABASE_URL: ${DATABASE_URL}
      dockerfile: Dockerfile
    container_name: baruashub-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    environment:
      - TZ=Asia/Kuala_Lumpur
    depends_on:
      - db
    volumes:
      - /opt/baruashub/StudexHub/infra:/app/infra

  db:
    image: postgres:16-alpine
    container_name: baruashub-db
    restart: unless-stopped
    environment:
      - TZ=Asia/Kuala_Lumpur
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - baruashub_postgres_data:/var/lib/postgresql/data

  ops-bot:
    build:
      context: ../../ops-bot
    container_name: studexhub-ops-bot
    restart: unless-stopped
    env_file:
      - .env.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/baruashub/StudexHub/storage/backups:/backups
    network_mode: host

volumes:
  baruashub_postgres_data:
